api_key:
- credentials: xrd:secret
  key: /home/bertvi/x/work/gofore_private_key
  roles:
  - XROAD_SYSTEM_ADMINISTRATOR
  - XROAD_SERVICE_ADMINISTRATOR
  - XROAD_SECURITY_OFFICER
  - XROAD_REGISTRATION_OFFICER
  url: https://localhost:4000/api/v1/api-keys
logging:
  file: /var/log/xroad/xrdsst.log
  level: INFO
security_server:
- api_key: X-Road-apikey token=<API_KEY>
  certificates:
    - /home/bertvi/x/ss3-sign.pem
    - /home/bertvi/x/ss3-auth.pem
  configuration_anchor: /etc/xroad/configuration-anchor3.xml
  name: ss3
  owner_dn_country: EE
  owner_dn_org: ACME
  owner_member_class: GOV
  owner_member_code: 1234
  security_server_code: ss3
  software_token_id: 0
  software_token_pin: 1234
  url: https://ss3:4000/api/v1
  clients:
    - member_class: GOV
      member_code: 1234
      subsystem_code: TEST
      connection_type: HTTP
      service_descriptions:
        - url: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator-gradle-plugin/samples/local-spec/petstore-v3.0.yaml
          rest_service_code: Petstore
          type: OPENAPI3
          access:
            - TEST
          services:
            - service_code: Petstore
              access:
                - TEST