api-key:
- key: /home/bertvi/x/work/gofore_private_key
  roles:
  - <ROLE>
  - <ROLE>
  url: https://localhost:4000/api/v1/api-keys
logging:
- file: /var/log/xroad/xrdsst.log
  level: INFO
security-server:
- api_key: <X-Road-apikey token=API_KEY>
  configuration_anchor: /etc/xroad/configuration-anchor.xml
  name: ss3
  owner_dn_country: EE
  owner_dn_org: ORG
  owner_member_class: GOV
  owner_member_code: 1234
  security_server_code: SS3
  software_token_id: 0
  software_token_pin: 1234
  url: https://ss3:4000/api/v1
- api_key: <X-Road-apikey token=API_KEY>
  configuration_anchor: /etc/xroad/configuration-anchor.xml
  name: ss4
  owner_dn_country: EE
  owner_dn_org: ORG
  owner_member_class: GOV
  owner_member_code: 1234
  security_server_code: SS4
  software_token_id: 0
  software_token_pin: 1234
  url: https://ss4:4000/api/v1