### Security Server Toolkit Configuration Settings

security-server:
  - name: ss1
    url: https://ss1:4000/api/v1
    api_key: X-Road-apikey token=6189108b-7a1d-4bce-a539-265eef3f6a6a
    configuration_anchor: /etc/xroad/configuration-anchor.xml
    owner_member_class: GOV
    owner_member_code: 1234
    security_server_code: SS1
    software_token_pin: 1234

  - name: ss3
    url: https://ss3:4000/api/v1
    api_key: X-Road-apikey token=38224e14-f5b3-4fc9-bba8-ca953c250f1c
    configuration_anchor: /etc/xroad/configuration-anchor.xml
    owner_member_class: GOV
    owner_member_code: 1234
    security_server_code: SS1
    software_token_pin: 1234

  - name: ss4
    url: https://ss4:4000/api/v1
    api_key: X-Road-apikey token=1f31e3fa-4878-44fd-91f3-f703cc472d5a
    configuration_anchor: /etc/xroad/configuration-anchor.xml
    owner_member_class: GOV
    owner_member_code: 1234
    security_server_code: SS1
    software_token_pin: 1234

