### Security Server Toolkit Configuration Settings

logging:
  - file: /path/to/xrdsst.log
    level: INFO

security-server:
  - name: <SECURITY_SERVER_NAME>
    url: https://<SECURITY_SERVER_FQDN_OR_IP>:4000/api/v1
    api_key: X-Road-apikey token=<API_KEY>
    configuration_anchor: /path/to/configuration-anchor.xml
    owner_member_class: <MEMBER_CLASS>
    owner_member_code: <MEMBER_CODE>
    security_server_code: <SERVER_CODE>
    software_token_id: 0 # <SOFT_TOKEN_ID> -- default software token ID is zero
    software_token_pin: <SOFT_TOKEN_PIN>

  - name: <SECURITY_SERVER_NAME>
    url: https://<SECURITY_SERVER_FQDN_OR_IP>:4000/api/v1
    api_key: X-Road-apikey token=<API_KEY>
    configuration_anchor: /path/to/configuration-anchor.xml
    owner_member_class: <MEMBER_CLASS>
    owner_member_code: <MEMBER_CODE>
    security_server_code: <SERVER_CODE>
    software_token_id: 0 # <SOFT_TOKEN_ID> -- default software token ID is zero
    software_token_pin: <SOFT_TOKEN_PIN>

