admin_credentials: XRDSST_CREDENTIALS
ssh_access:
  user: XRDSST_SSH_USER
  private_key: XRDSST_SSH_KEY
security_server:
- api_key: XRDSST_API_KEY
  api_key_url: https://localhost:4000/api/v1/api-keys
  admin_credentials: XRDSST_CREDENTIALS
  configuration_anchor: /home/alberto/Downloads/configuration_anchor_DEV_internal_UTC_2021-06-11_10_12_08.xml
  certificates:
    - /home/alberto/Downloads/ss1-default-sign-key-sign-CSR-C8845FA09F91F2124727AD89C57901D1DAE47C6E-qeye69hi.pem
    - /home/alberto/Downloads/ss1-default-sign-key_COM_12345-sign-CSR-FFADE97F8C5776332504F68FFB554B79E8C6F942-fkaxygrg.pem
    - /home/alberto/Downloads/ss1-default-auth-key-auth-CSR-5F35949CC742013CFB633E272D0D33C09EF4DF37-f_cq590z.pem
  name: ss1
  owner_dn_country: FI
  owner_dn_org: NIIS
  owner_member_class: ORG
  owner_member_code: 111
  security_server_code: ss1
  software_token_id: 0
  software_token_pin: 1234
  fqdn: ss1
  url: https://ss1:4000/api/v1
  ssh_user: XRDSST_SSH_USER
  ssh_private_key: XRDSST_SSH_KEY
  tls_certificates:
    - /home/alberto/Downloads/certs/cert.pem
  certificate_operations_hash:
    - 8EA19FE5CDD100390353EB40F6D6C2C70FE0AAFD
    - 397401787220FCB20A2194DAD3066DF4A0C8C5A6
    - CF09F4944E0EC2B2E3B149C1AC9C0DD4990C62D6
  clients:
    - member_class: ORG
      member_code: 111
      member_name: NIIS
      subsystem_code: TEST
      connection_type: HTTP
      tls_certificates:
        - /home/alberto/Downloads/certs/cert.pem
      service_descriptions:
        - url: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator-gradle-plugin/samples/local-spec/petstore-v3.0.yaml
          type: OPENAPI3
          url_all: True
          timeout_all: True
          ssl_auth_all: False
          access:
            - DEV:COM:12345:SUBCOMPANY
            - DEV:security-server-owners
          services:
            - service_code: Petstore
              timeout: 60
              ssl_auth: False
              url: http://petstore.xxx
    - member_class: COM
      member_code: 12345
      member_name: COMPANY
      connection_type: HTTP
    - member_class: COM
      member_code: 12345
      member_name: COMPANY
      subsystem_code: SUBCOMPANY
      connection_type: HTTP