admin_credentials: XRDSST_CREDENTIALS
ssh_access:
  user: XRDSST_SSH_USER
  private_key: XRDSST_SSH_KEY
security_server:
- api_key: XRDSST_API_KEY
  api_key_url: https://localhost:4000/api/v1/api-keys
  admin_credentials: XRDSST_CREDENTIALS
  configuration_anchor: /home/alberto/Downloads/configuration_anchor_DEV_internal_UTC_2021-04-27_14_53_48.xml
  certificates:
    - /path/to/signcert
    - /path/to/authcert
  name: ss1
  owner_dn_country: FI
  owner_dn_org: COMPANY
  owner_member_class: COM
  owner_member_code: 12345
  security_server_code: ss1
  software_token_id: 0
  software_token_pin: 1234
  fqdn: ss1
  url: https://ss1:4000/api/v1
  ssh_user: alberto
  ssh_private_key: <SSH private key>
  clients:
    - member_class: COM
      member_code: 12345
      subsystem_code: SUBCOMPANY
      connection_type: HTTP
      service_descriptions:
        - url: https://api.stats.x-road.global/v1
          rest_service_code: KOE
          type: REST
          access:
            - SUBNIIS
          url_all: https://
          timeout_all: 60
          ssl_auth_all: false
          services:
            - service_code: KOE
              access:
                - DEV:ORG:111:SUBNIIS
              timeout: 60
              ssl_auth: false
              url: https://api.stats.x-road.global/v1
          endpoints:
            - path: /testPath
              method: POST
              access:
                - DEV:ORG:111:SUBNIIS
                - DEV:security-server-owners
            - path: /getPath
              method: GET
              access:
                - DEV:ORG:111:SUBNIIS