admin_credentials: TOOLKIT_ADMIN_CREDENTIALS
ssh_access:
  user: TOOLKIT_SSH_USER
  private_key: TOOLKIT_SSH_PRIVATE_KEY
security_server:
- api_key: TOOLKIT_SS3_API_KEY
  api_key_url: https://localhost:4000/api/v1/api-keys
  certificates:
    - /home/bertvi/x/ss3-default-sign-key-sign-CSR-119CA86EBCA44A938177A5D79DD98031AB5024F9-3_9rwe6q.pem
    - /home/bertvi/x/ss3-default-sign-key_COM_222-sign-CSR-2BE518043E950DF05E945AEDA49A3AE298D37DAB-gwg4pox1.pem
    - /home/bertvi/x/ss3-default-auth-key-auth-CSR-889C121EF5BAEB5ACDCD51AA8896AD8BA485F78E-sw3iq9x5.pem
  configuration_anchor: /etc/xroad/configuration-anchor3.xml
  name: ss3
  owner_dn_country: EE
  owner_dn_org: ACME
  owner_member_class: GOV
  owner_member_code: 1234
  security_server_code: ss3
  software_token_id: 0
  software_token_pin: 1234
  fqdn: ss3
  url: https://ss3:4000/api/v1
  clients:
    - member_class: GOV
      member_code: 1234
      member_name: NIIS
      subsystem_code: TEST
      connection_type: HTTP
      local_groups:
        - code: <LOCAL_GROUP_CODE>
          description: <LOCAL_GROUP_DESCRIPTION>
          members:
            - <MEMBER_ID>
      service_descriptions:
        - url: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator-gradle-plugin/samples/local-spec/petstore-v3.0.yaml
          rest_service_code: Petstore
          type: OPENAPI3
          access:
            - DEV:security-server-owners
          url_all: False
          timeout_all: False
          ssl_auth_all: False
          services:
            - service_code: Petstore
              access:
                - DEV:security-server-owners
              timeout: 120
              ssl_auth: False
              url: http://petstore.xxx
          endpoints:
            - path: /testPath
              method: POST
              access:
                - DEV:security-server-owners
        - url: http://10.249.34.187/managementservices.wsdl
          type: WSDL
          access:
            - DEV:security-server-owners
          url_all: False
          timeout_all: False
          ssl_auth_all: False
          services:
            - service_code: ClientReg
              access:
                - DEV:security-server-owners
              timeout: 120
              ssl_auth: False
              url: http://petstore.xxx
    - member_class: GOV
      member_code: 1234
      member_name: NIIS
      subsystem_code: MANAGEMENT
      connection_type: HTTP
      service_descriptions:
        - url: http://10.249.34.187/managementservices.wsdl
          type: WSDL
          access:
            - DEV:security-server-owners
          url_all: False
          timeout_all: False
          ssl_auth_all: False
          services:
            - service_code: ClientReg
              access:
                - DEV:security-server-owners
              timeout: 120
              ssl_auth: False
              url: http://petstore.xxx
    - member_class: COM
      member_code: 222
      member_name: FRUIT
      connection_type: HTTP