admin_credentials: XRDSST_CREDENTIALS
ssh_access:
  user: XRDSST_SSH_USER
  private_key: XRDSST_SSH_KEY
security_server:
- api_key: XRDSST_API_KEY
  api_key_url: https://localhost:4000/api/v1/api-keys
  admin_credentials: XRDSST_CREDENTIALS
  configuration_anchor: /home/alberto/Downloads/configuration_anchor_DEV_internal_UTC_2021-05-25_10_31_37.xml
  certificates:
    - /home/alberto/Downloads/ss1-default-sign-key-sign-CSR-0A1038BB0C26FD051A24F77522EDC4D9207E0173-n8rav153.pem
    - /home/alberto/Downloads/ss1-default-sign-key_COM_12345-sign-CSR-7E4F72ED40C48F5BA59C7EE133DAC0D2791D7311-ldd7wxsd.pem
    - /home/alberto/Downloads/ss1-default-auth-key-auth-CSR-807683DBE511838892EDA5EC9A1F448DED129644-7axjl115.pem
  name: ss1
  owner_dn_country: FI
  owner_dn_org: NIIS
  owner_member_class: ORG
  owner_member_code: 111
  security_server_code: ss1
  software_token_id: 0
  software_token_pin: 1234
  fqdn: ss1
  url: https://ss1:4000/api/v1
  ssh_user: XRDSST_SSH_USER
  ssh_private_key: XRDSST_SSH_KEY
  clients:
    - member_class: ORG
      member_code: 111
      member_name: NIIS
      subsystem_code: SUBNIIS
      connection_type: HTTP
      service_descriptions:
        - url: http://10.54.135.88/managementservices.wsdl
          rest_service_code: None
          type: WSDL
          access:
              - DEV:security-server-owners
          url_all: True
          timeout_all: True
          ssl_auth_all: True
          services:
            - service_code: clientReg
              access:
                - DEV:security-server-owners
              timeout: 60
              ssl_auth: False
              url: https://10.54.135.88:4002/managementservice/manage/
            - service_code: clientDeletion
              access:
                - DEV:security-server-owners
              timeout: 60
              ssl_auth: False
              url: https://10.54.135.88:4002/managementservice/manage/
    - member_class: COM
      member_code: 12345
      member_name: COMPANY
      connection_type: HTTPS
