admin_credentials: <SECURITY_SERVER_CREDENTIALS>
ssh_access:
  user: <SSH_USER>
  private_key: /path/to/ssh_private_key
security_server:
- api_key: X-Road-apikey token=<API_KEY>
  api_key_roles:
  - XROAD_SYSTEM_ADMINISTRATOR
  - XROAD_SERVICE_ADMINISTRATOR
  - XROAD_SECURITY_OFFICER
  - XROAD_REGISTRATION_OFFICER
  api_key_url: https://localhost:4000/api/v1/api-keys
  admin_credentials:
  configuration_anchor: /path/to/configuration-anchor.xml
  certificates:
    - /path/to/signcert
    - /path/to/authcert
  name: <SECURITY_SERVER_NAME>
  owner_dn_country: <OWNER_DISTINGUISHED_NAME_COUNTRY>
  owner_dn_org: <OWNER_DISTINGUISHED_NAME_ORGANIZATION>
  owner_member_class: <MEMBER_CLASS>
  owner_member_code: <MEMBER_CODE>
  security_server_code: <SERVER_CODE>
  software_token_id: <SOFT_TOKEN_ID>
  software_token_pin: <SOFT_TOKEN_PIN>
  fqdn: <SECURITY_SERVER_EXTERNAL_FQDN>
  url: https://<SECURITY_SERVER_INTERNAL_FQDN_OR_IP>:4000/api/v1
  ssh_user: <SSH_USER>
  ssh_private_key: /path/to/ssh_private_key
  clients:
    - member_class: <MEMBER_CLASS>
      member_code: <MEMBER_CODE>
      subsystem_code: <SUBSYSTEM_CODE>
      connection_type: <CONNECTION_TYPE>
      service_descriptions:
        - url: <SERVICE_DESCRIPTION_URL>
          rest_service_code: <REST_SERVICE_CODE>
          type: <SERVICE_TYPE>
          access:
            - <SUBSYSTEM_CODE>
          url_all: <SERVICE_URL_FOR_ALL>
          timeout_all: <SERVICE_TIMEOUT_FOR_ALL>
          ssl_auth_all: <SERVICE_USE_SSL_AUTH_FOR_ALL>
          services:
            - service_code: <SERVICE_CODE>
              access:
                - <SUBSYSTEM_CODE>
              timeout: <SERVICE_TIMEOUT>
              ssl_auth: <SERVICE_USE_SSL_AUTH>
              url: <SERVICE_URL>