admin_credentials: XRDSST_CREDENTIALS
ssh_access:
  user: XRDSST_SSH_USER
  private_key: XRDSST_SSH_KEY
security_server:
- api_key: XRDSST_API_KEY
  api_key_url: https://localhost:4000/api/v1/api-keys
  admin_credentials: XRDSST_CREDENTIALS
  configuration_anchor: /home/alberto/Downloads/configuration_anchor_DEV_internal_UTC_2021-05-13_09_54_40.xml
  certificates:
    - /home/alberto/Downloads/ss1-default-sign-key_COM_12345-sign-CSR-A85D5307A44DB6847E58920D13A9C6D2731E3726-ciqvwyoz.pem
  name: ss1
  owner_dn_country: FI
  owner_dn_org: NIIS
  owner_member_class: ORG
  owner_member_code: 111
  security_server_code: ss1
  software_token_id: 0
  software_token_pin: 1234
  fqdn: ss1
  url: https://ss1:4000/api/v1
  ssh_user: XRDSST_SSH_USER
  ssh_private_key: XRDSST_SSH_KEY
  clients:
    - member_class: ORG
      member_code: 111
      member_name: NIIS
      subsystem_code: TEST
      connection_type: HTTP
	  local_groups:
        - code: testGroup
          description: Description test group
          members:
            - DEV:COM:12345:SUBCOMPANY
      service_descriptions:
        - url: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator-gradle-plugin/samples/local-spec/petstore-v3.0.yaml
          rest_service_code: Petstore
          type: OPENAPI3
          access:
              - DEV:security-server-owners
          url_all: True
          timeout_all: True
          ssl_auth_all: False
          services:
            - service_code: Petstore
              access:
                - DEV:ORG:111:SUBNIIS
                - DEV:security-server-owners
                - DEV:ORG:0000:SUBORGANIZATION
              timeout: 60
              ssl_auth: False
              url: http://petstore.xxx
          endpoints:
            - path: /testPath
              method: POST
              access:
                - DEV:security-server-owners
                - DEV:ORG:0000:SUBORGANIZATION
            - path: /getPath
              method: GET
              access:
                - DEV:ORG:111:SUBNIIS
        - url: http://10.54.135.88/managementservices.wsdl
          rest_service_code: None
          type: WSDL
          access:
              - DEV:security-server-owners
          url_all: True
          timeout_all: True
          ssl_auth_all: False
          services:
            - service_code: clientReg
              access:
                - DEV:ORG:111:SUBNIIS
                - DEV:ORG:0000:SUBORGANIZATION
              timeout: 40
              ssl_auth: False
              url: http://10.54.135.88/managementservices.wsdl
    - member_class: COM
      member_code: 12345
      member_name: COMPANY
      connection_type: HTTPS
