admin_credentials: xrd:secret
ssh_access:
  user: <SSH_USER>
  private_key: /path/to/ssh_private_key
security_server:
- api_key: f9d61379-9250-43ba-891e-6c032b93b536
  api_key_url: https://ss1:4000/api/v1/api-keys
  admin_credentials: xrd:secret
  configuration_anchor: /home/alberto/Downloads/configuration_anchor_DEV_internal_UTC_2021-04-15_12_31_50.xml
  certificates:
    - /path/to/signcert
    - /path/to/authcert
  name: ss1
  owner_dn_country: FI
  owner_dn_org: Companies
  owner_member_class: COM
  owner_member_code: 12345
  security_server_code: ss1
  software_token_id: 0
  software_token_pin: 1234
  fqdn: ss1
  url: https://ss1:4000/api/v1
  ssh_user: alberto
  ssh_private_key: <SSH private key>
  clients:
    - member_class: COM
      member_code: 12345
      subsystem_code: SUBCOMPANY
      connection_type: HTTP
      service_descriptions:
        - url: https://api.stats.x-road.global/v1
          rest_service_code: KOE
          type: REST
          access:
            - TESTCOMPANY
          url_all: https://
          timeout_all: 60
          ssl_auth_all: false
          endpoints:
            - path: /testPath
              method: POST
            - path: /getPath
              method: GET
        - url: http://10.54.135.88/managementservices.wsdl
          rest_service_code: <code>
          type: WSDL
          access:
            - TESTCOMPANY
          url_all: http://
          timeout_all: 60
          ssl_auth_all: false
          services:
            - service_code: KOE
              access:
                - SUBCOMPANY
              timeout: 60
              ssl_auth: true
              url: https://api.stats.x-road.global/v1
          endpoints:
            - path: /testPath
              method: POST
